/**
 * Transactional email — Infobip Email API (V4).
 *
 * Every outbound transactional email in the platform flows through `sendEmail`
 * here so we have a single, SMTP-independent channel with one place to handle
 * authentication, sender formatting, and error logging.
 *
 * Endpoint:  POST {INFOBIP_BASE_URL}/email/4/messages
 * Auth:      Authorization: App {INFOBIP_API_KEY}   (scheme is "App", NOT "Bearer")
 *
 * Configured via Railway env vars:
 *   INFOBIP_BASE_URL      e.g. https://55e51x.api.infobip.com
 *   INFOBIP_API_KEY       (secret)
 *   INFOBIP_SENDER_EMAIL  e.g. noreply@edusaga360.com
 *
 * The higher-level helpers (sendInviteEmail / sendPasswordResetEmail) never mint
 * Supabase recovery tokens themselves — the caller passes a fully-built link so
 * the emailed link and any copyable fallback stay on the SAME token.
 */

/** True when the Infobip env vars needed to send are present. */
export function isEmailConfigured(): boolean {
  return !!(process.env.INFOBIP_API_KEY && process.env.INFOBIP_BASE_URL);
}

/** Resolve the "sender" field, adding a friendly name when only a bare address is set. */
function resolveSender(): string {
  const raw = process.env.INFOBIP_SENDER_EMAIL || 'noreply@edusaga360.com';
  // Already in "Name <addr>" form? Leave as-is. Otherwise wrap with a display name.
  return raw.includes('<') ? raw : `EduSaga 360 <${raw}>`;
}

export interface EmailAttachment {
  fileName: string;
  contentType: string;
  contentBase64: string;
}

export interface SendEmailInput {
  to: string;
  subject: string;
  html: string;
  /** Optional Infobip attachments (e.g. payslip PDF retained after secure-link expiry). */
  attachments?: EmailAttachment[];
}

/**
 * Core sender. Sends one transactional email via Infobip's V4 messages API.
 *
 * - Resolves on the Infobip acknowledgement (status PENDING_ENROUTE + messageId);
 *   final delivery status arrives later via delivery-report webhooks, not here.
 * - Throws on a non-2xx response, logging the status + body so failures surface
 *   in Railway deploy logs.
 * - When Infobip is not configured, logs a warning and resolves to null instead
 *   of throwing, so local/dev/test environments don't break on missing secrets.
 */
export async function sendEmail({ to, subject, html, attachments }: SendEmailInput): Promise<unknown> {
  const baseUrl = process.env.INFOBIP_BASE_URL;
  const apiKey = process.env.INFOBIP_API_KEY;

  if (!baseUrl || !apiKey) {
    console.warn(
      `[EMAIL] Infobip not configured (INFOBIP_API_KEY / INFOBIP_BASE_URL missing) — skipping email to ${to} ("${subject}")`,
    );
    return null;
  }

  const content: Record<string, unknown> = { subject, html };
  if (attachments?.length) {
    content.attachments = attachments.map((a) => ({
      fileName: a.fileName,
      contentType: a.contentType,
      content: a.contentBase64,
    }));
  }

  const endpoint = `${baseUrl.replace(/\/+$/, '')}/email/4/messages`;
  const res = await fetch(endpoint, {
    method: 'POST',
    headers: {
      'Authorization': `App ${apiKey}`,
      'Content-Type': 'application/json',
      'Accept': 'application/json',
    },
    body: JSON.stringify({
      messages: [
        {
          sender: resolveSender(),
          destinations: [{ to: [{ destination: to }] }],
          content,
        },
      ],
    }),
  });

  const text = await res.text();
  if (!res.ok) {
    console.error(`[EMAIL] Infobip send failed for ${to} ("${subject}"): ${res.status} ${text}`);
    throw new Error(`Infobip email failed: ${res.status} ${text}`);
  }

  console.log(`[EMAIL] Infobip accepted email to ${to} ("${subject}"): ${res.status} ${text}`);
  try {
    return JSON.parse(text);
  } catch {
    return text;
  }
}

/** Simple password-reset helper (link already generated by the caller). */
export const sendPasswordReset = (to: string, resetLink: string) =>
  sendEmail({
    to,
    subject: 'Reset your EduSaga 360 password',
    html: `<p>Click the link below to reset your password:</p>
           <p><a href="${resetLink}">Reset Password</a></p>
           <p>If you didn't request this, you can safely ignore this email.</p>`,
  });

/** Simple welcome helper. */
export const sendWelcome = (to: string, name: string) =>
  sendEmail({
    to,
    subject: 'Welcome to EduSaga 360',
    html: `<p>Hi ${name}, welcome to EduSaga 360! We're glad to have you on board.</p>`,
  });

/** School-onboarding invitation (register a new school + start trial). */
export async function sendInviteEmail(opts: {
  recipient_email: string;
  recipient_name: string;
  school_name?: string | null;
  inviteLink: string;
  message?: string | null;
}): Promise<unknown> {
  const { recipient_email, recipient_name, school_name, inviteLink, message } = opts;
  const schoolLine = school_name ? `<p>School: <strong>${school_name}</strong></p>` : '';
  const customMsg = message ? `<p style="color:#555">${message}</p>` : '';
  const html = `
    <div style="font-family:sans-serif;max-width:560px;margin:0 auto">
      <h2 style="color:#059669">You're invited to EduSaga 360</h2>
      <p>Hi ${recipient_name},</p>
      ${customMsg}
      ${schoolLine}
      <p>Click the button below to set up your school's account and start your free trial:</p>
      <p style="text-align:center;margin:32px 0">
        <a href="${inviteLink}" style="background:#059669;color:#fff;padding:14px 28px;border-radius:8px;text-decoration:none;font-weight:bold">
          Accept Invitation
        </a>
      </p>
      <p style="font-size:12px;color:#999">This link expires in 7 days. If you did not expect this email, you can safely ignore it.</p>
    </div>`;

  return sendEmail({ to: recipient_email, subject: `You're invited to try EduSaga 360`, html });
}

/**
 * Password-reset / set-password email.
 *
 * `actionLink` MUST be a recovery link the caller already generated
 * (e.g. via `supabase.auth.admin.generateLink({ type: 'recovery' })`) so the
 * emailed link and any copyable fallback share one — and only one — valid token.
 */
export async function sendPasswordResetEmail(opts: {
  recipient_email: string;
  recipient_name?: string | null;
  actionLink: string;
  /** When true, phrases the email as a first-time "set your password" invite. */
  isInvite?: boolean;
}): Promise<unknown> {
  const { recipient_email, recipient_name, actionLink, isInvite } = opts;
  const name = recipient_name || 'there';
  const heading = isInvite ? 'Set up your EduSaga 360 password' : 'Reset your EduSaga 360 password';
  const intro = isInvite
    ? 'An administrator has created an account for you. Click the button below to set your password and sign in:'
    : 'We received a request to reset your EduSaga 360 password. Click the button below to choose a new one:';
  const cta = isInvite ? 'Set Password' : 'Reset Password';
  const html = `
    <div style="font-family:sans-serif;max-width:560px;margin:0 auto">
      <h2 style="color:#059669">${heading}</h2>
      <p>Hi ${name},</p>
      <p>${intro}</p>
      <p style="text-align:center;margin:32px 0">
        <a href="${actionLink}" style="background:#059669;color:#fff;padding:14px 28px;border-radius:8px;text-decoration:none;font-weight:bold">
          ${cta}
        </a>
      </p>
      <p style="font-size:12px;color:#999">This link can only be used once and expires shortly. If you didn't request this, you can safely ignore this email and your password will stay the same.</p>
    </div>`;

  return sendEmail({
    to: recipient_email,
    subject: isInvite ? 'Set up your EduSaga 360 account' : 'Reset your EduSaga 360 password',
    html,
  });
}
