/**
 * Golden-file tests for the Saudi ZATCA invoice HTML template.
 *
 * The HTML is the input to the PDF renderer; it captures layout, bilingual text,
 * VAT summaries, QR placement and Hijri date formatting. Chromium font subsets and
 * PDF metadata are not part of this snapshot.
 */
import { describe, it, expect, beforeAll } from 'vitest';
import QRCode from 'qrcode';
import type { InvoiceData } from '../../packs/sa/vat.js';
import {
  buildInvoiceHTML,
  generateUBLXml,
  generateInvoiceHash,
  signInvoice,
  generateTLVQR,
  TenantData,
} from '../../services/zatca.js';
import { golden } from './support/golden.js';

beforeAll(() => {
  process.env.TZ = 'UTC';
  // Force the fallback signature so the QR payload is deterministic.
  delete process.env.ZATCA_PRIVATE_KEY;
});

const baseTenant: TenantData = {
  name: 'Al Noor International School',
  name_ar: 'مدرسة النور العالمية',
  legal_name_en: 'Al Noor International School',
  legal_name_ar: 'مدرسة النور العالمية',
  vat_number: '300000000000003',
  cr_number: '1010101010',
  address: 'King Fahd Road, Riyadh',
  address_ar: 'طريق الملك فهد، الرياض',
  address_en: 'King Fahd Road, Riyadh',
  city: 'Riyadh',
  country_code: 'SA',
  country_subentity_code: 'SA-01',
  phone: '966500000000',
  email: 'info@alnoor.edu.sa',
};

const baseInvoice: InvoiceData = {
  uuid: '11111111-1111-1111-1111-111111111111',
  icv: 1,
  previous_invoice_hash: '0'.repeat(64),
  invoice_number: 'INV-2026-000001',
  document_type: 'invoice',
  issue_date: '2026-06-18T00:00:00Z',
  subtotal: 1000,
  vat_amount: 150,
  total_amount: 1150,
  paid_amount: 0,
  discount_amount: 0,
  student_name: 'Sara Ahmed',
  buyer_name: 'Sara Ahmed',
  buyer_address: 'Riyadh, Saudi Arabia',
  items: [
    {
      description: 'Tuition',
      description_en: 'Tuition',
      description_ar: 'رسوم دراسية',
      quantity: 1,
      unit_price_net: 1000,
      vat_rate: 0.15,
      vat_amount: 150,
      line_total_gross: 1150,
      vat_category: 'standard',
      vat_category_code: 'S',
      discount: 0,
    },
  ],
};

/**
 * The QR image data URL is generated by the `qrcode` PNG encoder. PNG output is
 * byte-stable in practice but depends on renderer internals, so we normalise
 * the embedded `src="data:image/png;base64,..."` to a fixed marker. The QR
 * payload itself is snapshotted separately in sa-zatca-golden.test.ts.
 *
 * Normalised values:
 *   - QR data URL → {{QR_DATA_URL}}
 */
function normaliseHtml(html: string): string {
  return html.replace(
    /src="data:image\/png;base64,[A-Za-z0-9+/=]+"/g,
    'src="{{QR_DATA_URL}}"',
  );
}

async function snapshotHtml(name: string, invoice: InvoiceData) {
  const xml = generateUBLXml(invoice, baseTenant);
  const signature = signInvoice(generateInvoiceHash(xml));
  const tlv = generateTLVQR(invoice, baseTenant, signature);
  const qrDataUrl = await QRCode.toDataURL(tlv, {
    errorCorrectionLevel: 'M',
    margin: 1,
    width: 180,
  });
  const html = buildInvoiceHTML(invoice, baseTenant, qrDataUrl);
  golden(name, normaliseHtml(html), 'html');
}

describe('ZATCA invoice HTML golden snapshots', () => {
  it('simplified tax invoice HTML is byte-stable', async () => {
    await snapshotHtml('sa-zatca-simplified-html', {
      ...baseInvoice,
      invoice_type: 'simplified',
    } as InvoiceData);
  });

  it('standard tax invoice HTML is byte-stable', async () => {
    await snapshotHtml('sa-zatca-standard-html', {
      ...baseInvoice,
      invoice_type: 'standard',
    } as InvoiceData);
  });
});
