import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

const STORAGE_KEY = 'pp_lang';

export const translations = {
  en: {
    // Shell / nav
    parentPortal: 'Parent Portal',
    dashboard: 'Dashboard',
    studentProgress: 'Student Progress',
    attendance: 'Attendance',
    feesBilling: 'Fees & Billing',
    announcements: 'Announcements',
    homework: 'Homework',
    messages: 'Messages',
    signOut: 'Sign Out',
    switchToArabic: 'العربية',
    switchToEnglish: 'English',

    // Dashboard
    welcome: 'Welcome',
    parentPortalDashboard: 'Attendance, fees, and school messages for your children.',
    parentPortalEyebrow: 'Parent portal',
    signInSubtitle: 'Sign in to follow your children',
    loginLead: 'Attendance, fees, grades, and school messages — in one place.',
    more: 'More',
    navigation: 'Main menu',
    inbox: 'Inbox',
    noMessagesYet: 'No messages yet',
    writeFirstMessage: 'Write a note to the school office — it will appear in this inbox.',
    darkMode: 'Dark mode',
    lightMode: 'Light mode',
    viewProgress: 'Progress',
    viewAttendance: 'Attendance',
    viewFees: 'Fees',
    myChildren: 'My Children',
    attendanceRate: 'Attendance Rate',
    outstandingFees: 'Outstanding Fees',
    notifications: 'Notifications',
    noStudentsLinked: 'No students linked to your account yet.',
    contactAdmin: 'Please contact your school administrator.',
    linkChildLead: 'Your account is active. Ask the school office to link your child so attendance, grades, and fees can appear here.',
    messageSchool: 'Message the school office',
    noDataYet: 'No data yet',
    averageGrade: 'Average grade',
    homeworkOverdue: 'Overdue homework',
    attendanceTrend: 'Attendance trend',
    attendanceTrendHint: 'Daily attendance rate for the latest school days.',
    subjectScores: 'Latest subject scores',
    subjectScoresHint: 'Most recent mark in each subject.',
    homeworkSnapshot: 'Homework snapshot',
    allChildren: 'All children',
    date: 'Date',
    notes: 'Notes',
    present: 'Present',
    absent: 'Absent',
    late: 'Late',
    excused: 'Excused',
    highPriority: 'High priority',
    assigned: 'Assigned',
    submitted: 'Submitted',
    graded: 'Graded',
    sendMessage: 'Send a message',
    subject: 'Subject',
    messageBody: 'Message',
    send: 'Send',
    messageSent: 'Message sent',
    messageSendFailed: 'Could not send the message',
    from: 'From',
    general: 'General',
    academic: 'Academic',

    // Login
    email: 'Email',
    password: 'Password',
    signIn: 'Sign In',
    loginFailed: 'Login failed',

    // Access denied
    accessDenied: 'Access Denied',
    accessDeniedDesc: 'This portal is for parents only. Please contact your school administrator for access.',

    // Fees
    totalOutstanding: 'Total Outstanding',
    noStudentsLinkedAccount: 'No students are linked to your account yet.',
    contactSchoolLink: 'Contact the school to link your child to your account.',
    noInvoices: 'No invoices yet.',
    invoicesWillAppear: 'Invoices issued by the school will appear here.',
    invoiceNo: 'Invoice #',
    student: 'Student',
    due: 'Due',
    total: 'Total',
    balance: 'Balance',
    status: 'Status',
    invoice: 'Invoice',
    downloadError: 'Could not download the invoice',
    notAuthorizedInvoice: 'Not authorized to view this invoice',
    feesPageHint: 'Filter by child, payment status, and due date. Pay open bills or download a receipt for paid ones.',
    payNow: 'Pay now',
    payError: 'Could not open the payment page',
    receipt: 'Receipt',
    receiptDownloaded: 'Receipt downloaded',
    receiptError: 'Could not download the receipt',
    actions: 'Actions',
    invoicesCount: 'invoices',
    noMatchingInvoices: 'No invoices match these filters',
    noMatchingInvoicesHint: 'Try another status or due-date range, or clear the filters.',

    // Status labels
    paid: 'Paid',
    partial: 'Partially Paid',
    unpaid: 'Unpaid',
    overdue: 'Overdue',
    cancelled: 'Cancelled',

    // Placeholder pages
    studentProgressTitle: 'Student Progress',
    progressWillAppear: 'Student grades and progress reports will appear here.',
    progressDataNote: 'Data will be available once the school adds grade records.',
    attendanceRecords: 'Attendance Records',
    attendanceWillAppear: 'Attendance records for your children will appear here.',
    attendanceDataNote: 'Data will be available once the school records attendance.',
    attendancePageHint: 'Filter by child, status, and date, then export a PDF report.',
    filterStatus: 'Status',
    allStatuses: 'All',
    dateFrom: 'From date',
    dateTo: 'To date',
    last7Days: 'Last 7 days',
    last30Days: 'Last 30 days',
    thisMonth: 'This month',
    exportPdf: 'Export PDF',
    clearFilters: 'Clear filters',
    showing: 'Showing',
    records: 'records',
    noMatchingAttendance: 'No records match these filters',
    noMatchingAttendanceHint: 'Try another status or date range, or clear the filters.',
    attendanceReport: 'Attendance report',
    generatedOn: 'Generated',
    childLabel: 'Child',
    allDates: 'All dates',
    schoolAnnouncements: 'School Announcements',
    announcementsWillAppear: 'School announcements and communications will appear here.',
    announcementsNote: 'Stay tuned for updates from your school.',
    homeworkAssignments: 'Homework & Assignments',
    homeworkWillAppear: 'Homework assignments will appear here.',
    homeworkNote: 'Teachers will post assignments that you can view and track.',
    messagesTitle: 'Messages',
    messagesWillAppear: 'Direct messaging with teachers will be available here.',
    messagesNote: 'You can read school messages and send a note to the office.',

    // Records hub tabs
    tabInvoices: 'Invoices',
    tabPayments: 'Payments',
    tabContracts: 'Contracts',
    tabAdmissionDocs: 'Admission docs',
    paymentHistory: 'Payment history',
    noPayments: 'No payments recorded yet.',
    noContracts: 'No enrollment contracts on file.',
    noAdmissionDocs: 'No admission application found for this child.',
    contractStatus: 'Contract',
    signedOn: 'Signed',
    applicationStage: 'Stage',
    documentChecklist: 'Required documents',
    uploaded: 'Uploaded',
    missing: 'Missing',
    viewDocument: 'View',

    // Canteen
    canteen: 'Canteen',
    canteenBalance: 'Wallet balance',
    canteenTopUp: 'Top up',
    canteenHistory: 'Spend history',
    canteenLowBalance: 'Low balance — consider topping up.',
    canteenTopUpHint: 'Add credit to your child\'s canteen card for cashless purchases.',
    topUpAmount: 'Amount (SAR)',
    topUpSuccess: 'Payment page opened — credit applies after payment.',
    noCanteenActivity: 'No canteen activity yet.',
    canteenAllergies: 'Food allergies',
    canteenAllergiesHint: 'Tell the school which foods your child cannot eat. Cashiers see an alert at the till.',
    canteenAllergiesSaved: 'Allergies saved. The canteen POS will warn staff.',
    allergenNuts: 'Nuts',
    allergenDairy: 'Dairy',
    allergenGluten: 'Gluten',
    allergenEggs: 'Eggs',
    allergenSoy: 'Soy',
    allergenFish: 'Fish',
    allergenShellfish: 'Shellfish',
    saveAllergies: 'Save allergies',

    // Store
    store: 'School store',
    storeHint: 'Uniforms, pool passes, and facility rentals — click and collect at school.',
    addToCart: 'Add',
    cart: 'Cart',
    checkout: 'Checkout',
    purchase: 'Buy',
    rent: 'Rent',
    collectAtSchool: 'Collect at school after payment',
    noStoreProducts: 'No products available right now.',
    noStoreOrders: 'No store orders yet.',
    orderReady: 'Ready to collect',
    orderPending: 'Awaiting payment',
    orderCollected: 'Collected',
    categoryUniform: 'Uniforms',
    categoryPool: 'Pool',
    categoryPlayground: 'Football pitch',
    categoryOther: 'Other',
    selectVariant: 'Select size',
    pickSlot: 'Choose a time',
    noSlots: 'No open times on this day.',
    slotTaken: 'Taken',
    searchStore: 'Search uniforms, pool, pitches…',
    cartEmpty: 'Your cart is empty',
    cartEmptyHint: 'Add a uniform or a rental, then check out here.',
    subtotal: 'Subtotal',
    myOrders: 'My orders',
    inStock: 'In stock',
    lowStock: 'Low stock',
    outOfStock: 'Out of stock',
    bookable: 'Timed booking',
    collectFrom: 'Collect from',
    addedToCart: 'Added to cart',
    selectVariantFirst: 'Choose a size first',
    catalog: 'Catalog',
  },
  ar: {
    // Shell / nav
    parentPortal: 'بوابة ولي الأمر',
    dashboard: 'الرئيسية',
    studentProgress: 'مستوى الطالب',
    attendance: 'الحضور',
    feesBilling: 'الرسوم والفواتير',
    announcements: 'الإعلانات',
    homework: 'الواجبات',
    messages: 'الرسائل',
    signOut: 'تسجيل الخروج',
    switchToArabic: 'العربية',
    switchToEnglish: 'English',

    // Dashboard
    welcome: 'مرحباً',
    parentPortalDashboard: 'الحضور والرسوم ورسائل المدرسة لأبنائك.',
    parentPortalEyebrow: 'بوابة ولي الأمر',
    signInSubtitle: 'سجّل الدخول لمتابعة أبنائك',
    loginLead: 'الحضور والرسوم والدرجات ورسائل المدرسة — في مكان واحد.',
    more: 'المزيد',
    navigation: 'القائمة الرئيسية',
    inbox: 'الوارد',
    noMessagesYet: 'لا توجد رسائل بعد',
    writeFirstMessage: 'اكتب ملاحظة إلى إدارة المدرسة — وستظهر في هذا الصندوق.',
    darkMode: 'الوضع الداكن',
    lightMode: 'الوضع الفاتح',
    viewProgress: 'المستوى',
    viewAttendance: 'الحضور',
    viewFees: 'الرسوم',
    myChildren: 'أبنائي',
    attendanceRate: 'نسبة الحضور',
    outstandingFees: 'الرسوم المستحقة',
    notifications: 'الإشعارات',
    noStudentsLinked: 'لا يوجد طلاب مرتبطون بحسابك بعد.',
    contactAdmin: 'يرجى التواصل مع إدارة المدرسة.',
    linkChildLead: 'حسابك نشط. اطلب من إدارة المدرسة ربط ابنك حتى تظهر هنا سجلات الحضور والدرجات والرسوم.',
    messageSchool: 'مراسلة إدارة المدرسة',
    noDataYet: 'لا بيانات بعد',
    averageGrade: 'متوسط الدرجات',
    homeworkOverdue: 'واجبات متأخرة',
    attendanceTrend: 'اتجاه الحضور',
    attendanceTrendHint: 'نسبة الحضور اليومية لأحدث أيام الدراسة.',
    subjectScores: 'أحدث درجات المواد',
    subjectScoresHint: 'آخر درجة مسجّلة في كل مادة.',
    homeworkSnapshot: 'ملخص الواجبات',
    allChildren: 'جميع الأبناء',
    date: 'التاريخ',
    notes: 'ملاحظات',
    present: 'حاضر',
    absent: 'غائب',
    late: 'متأخر',
    excused: 'بعذر',
    highPriority: 'أولوية عالية',
    assigned: 'مطلوب',
    submitted: 'مُسلَّم',
    graded: 'مُقيَّم',
    sendMessage: 'إرسال رسالة',
    subject: 'الموضوع',
    messageBody: 'الرسالة',
    send: 'إرسال',
    messageSent: 'تم إرسال الرسالة',
    messageSendFailed: 'تعذّر إرسال الرسالة',
    from: 'من',
    general: 'عام',
    academic: 'أكاديمي',

    // Login
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    signIn: 'تسجيل الدخول',
    loginFailed: 'فشل تسجيل الدخول',

    // Access denied
    accessDenied: 'تم رفض الوصول',
    accessDeniedDesc: 'هذه البوابة مخصصة لأولياء الأمور فقط. يرجى التواصل مع إدارة المدرسة للحصول على صلاحية الدخول.',

    // Fees
    totalOutstanding: 'إجمالي المستحق',
    noStudentsLinkedAccount: 'لا يوجد طلاب مرتبطون بحسابك بعد.',
    contactSchoolLink: 'تواصل مع المدرسة لربط ابنك بحسابك.',
    noInvoices: 'لا توجد فواتير بعد.',
    invoicesWillAppear: 'ستظهر هنا الفواتير الصادرة من المدرسة.',
    invoiceNo: 'رقم الفاتورة',
    student: 'الطالب',
    due: 'الاستحقاق',
    total: 'الإجمالي',
    balance: 'المتبقي',
    status: 'الحالة',
    invoice: 'الفاتورة',
    downloadError: 'تعذّر تنزيل الفاتورة',
    notAuthorizedInvoice: 'غير مصرح لك بعرض هذه الفاتورة',
    feesPageHint: 'صفّ حسب الابن وحالة الدفع وتاريخ الاستحقاق. ادفع الفواتير المفتوحة أو نزّل سند القبض للمدفوعة.',
    payNow: 'ادفع الآن',
    payError: 'تعذّر فتح صفحة الدفع',
    receipt: 'سند القبض',
    receiptDownloaded: 'تم تنزيل سند القبض',
    receiptError: 'تعذّر تنزيل سند القبض',
    actions: 'إجراءات',
    invoicesCount: 'فواتير',
    noMatchingInvoices: 'لا توجد فواتير مطابقة لعوامل التصفية',
    noMatchingInvoicesHint: 'جرّب حالة أو فترة استحقاق أخرى، أو امسح عوامل التصفية.',

    // Status labels
    paid: 'مدفوعة',
    partial: 'مدفوعة جزئياً',
    unpaid: 'غير مدفوعة',
    overdue: 'متأخرة',
    cancelled: 'ملغاة',

    // Placeholder pages
    studentProgressTitle: 'مستوى الطالب',
    progressWillAppear: 'ستظهر هنا درجات الطالب وتقارير المستوى.',
    progressDataNote: 'ستتوفر البيانات بمجرد إضافة المدرسة لسجلات الدرجات.',
    attendanceRecords: 'سجلات الحضور',
    attendanceWillAppear: 'ستظهر هنا سجلات حضور أبنائك.',
    attendanceDataNote: 'ستتوفر البيانات بمجرد تسجيل المدرسة للحضور.',
    attendancePageHint: 'صفّ حسب الابن والحالة والتاريخ، ثم صدّر تقريراً بصيغة PDF.',
    filterStatus: 'الحالة',
    allStatuses: 'الكل',
    dateFrom: 'من تاريخ',
    dateTo: 'إلى تاريخ',
    last7Days: 'آخر ٧ أيام',
    last30Days: 'آخر ٣٠ يوماً',
    thisMonth: 'هذا الشهر',
    exportPdf: 'تصدير PDF',
    clearFilters: 'مسح عوامل التصفية',
    showing: 'عرض',
    records: 'سجلات',
    noMatchingAttendance: 'لا توجد سجلات مطابقة لعوامل التصفية',
    noMatchingAttendanceHint: 'جرّب حالة أو فترة تاريخ أخرى، أو امسح عوامل التصفية.',
    attendanceReport: 'تقرير الحضور',
    generatedOn: 'تاريخ الإنشاء',
    childLabel: 'الابن',
    allDates: 'كل التواريخ',
    schoolAnnouncements: 'إعلانات المدرسة',
    announcementsWillAppear: 'ستظهر هنا إعلانات المدرسة والتواصل.',
    announcementsNote: 'ترقّب التحديثات من مدرستك.',
    homeworkAssignments: 'الواجبات والمهام',
    homeworkWillAppear: 'ستظهر هنا الواجبات المدرسية.',
    homeworkNote: 'سيقوم المعلمون بنشر المهام التي يمكنك عرضها ومتابعتها.',
    messagesTitle: 'الرسائل',
    messagesWillAppear: 'ستتوفر هنا المراسلة المباشرة مع المعلمين.',
    messagesNote: 'يمكنك قراءة رسائل المدرسة وإرسال ملاحظة إلى الإدارة.',

    tabInvoices: 'الفواتير',
    tabPayments: 'المدفوعات',
    tabContracts: 'العقود',
    tabAdmissionDocs: 'مستندات القبول',
    paymentHistory: 'سجل المدفوعات',
    noPayments: 'لا توجد مدفوعات مسجّلة بعد.',
    noContracts: 'لا توجد عقود تسجيل لهذا الطالب.',
    noAdmissionDocs: 'لا يوجد طلب قبول لهذا الطالب.',
    contractStatus: 'العقد',
    signedOn: 'تاريخ التوقيع',
    applicationStage: 'المرحلة',
    documentChecklist: 'الوثائق المطلوبة',
    uploaded: 'مرفوع',
    missing: 'مفقود',
    viewDocument: 'عرض',

    canteen: 'المقصف',
    canteenBalance: 'رصيد المحفظة',
    canteenTopUp: 'شحن',
    canteenHistory: 'سجل المشتريات',
    canteenLowBalance: 'رصيد منخفض — يُفضّل الشحن.',
    canteenTopUpHint: 'أضف رصيداً لبطاقة ابنك للشراء بدون نقد.',
    topUpAmount: 'المبلغ (ريال)',
    topUpSuccess: 'تم فتح صفحة الدفع — يُضاف الرصيد بعد الدفع.',
    noCanteenActivity: 'لا يوجد نشاط في المقصف بعد.',
    canteenAllergies: 'أنواع الحساسية الغذائية',
    canteenAllergiesHint: 'حدد الأطعمة التي لا يمكن لابنك تناولها. تظهر تنبيه للكاشير في نقطة البيع.',
    canteenAllergiesSaved: 'تم حفظ الحساسية. ستظهر تنبيهات في نقطة بيع المقصف.',
    allergenNuts: 'مكسرات',
    allergenDairy: 'ألبان',
    allergenGluten: 'غلوتين',
    allergenEggs: 'بيض',
    allergenSoy: 'صويا',
    allergenFish: 'سمك',
    allergenShellfish: 'محار',
    saveAllergies: 'حفظ الحساسية',

    store: 'المتجر المدرسي',
    storeHint: 'الزي المدرسي وتذاكر المسبح وإيجار الملاعب — استلام من المدرسة.',
    addToCart: 'إضافة',
    cart: 'السلة',
    checkout: 'الدفع',
    purchase: 'شراء',
    rent: 'إيجار',
    collectAtSchool: 'الاستلام من المدرسة بعد الدفع',
    noStoreProducts: 'لا توجد منتجات متاحة حالياً.',
    noStoreOrders: 'لا توجد طلبات بعد.',
    orderReady: 'جاهز للاستلام',
    orderPending: 'بانتظار الدفع',
    orderCollected: 'تم الاستلام',
    categoryUniform: 'الزي المدرسي',
    categoryPool: 'المسبح',
    categoryPlayground: 'ملعب كرة القدم',
    categoryOther: 'أخرى',
    selectVariant: 'اختر المقاس',
    pickSlot: 'اختر وقتاً',
    noSlots: 'لا توجد أوقات متاحة في هذا اليوم.',
    slotTaken: 'محجوز',
    searchStore: 'ابحث عن الزي أو المسبح أو الملاعب…',
    cartEmpty: 'سلتك فارغة',
    cartEmptyHint: 'أضف زياً أو إيجاراً ثم أكمل الدفع من هنا.',
    subtotal: 'المجموع الفرعي',
    myOrders: 'طلباتي',
    inStock: 'متوفر',
    lowStock: 'كمية محدودة',
    outOfStock: 'غير متوفر',
    bookable: 'حجز بموعد',
    collectFrom: 'الاستلام من',
    addedToCart: 'أُضيف إلى السلة',
    selectVariantFirst: 'اختر المقاس أولاً',
    catalog: 'المنتجات',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    try { return localStorage.getItem(STORAGE_KEY) || 'en'; } catch { return 'en'; }
  });
  const isRTL = lang === 'ar';

  useEffect(() => {
    if (typeof document !== 'undefined') {
      document.documentElement.lang = lang;
      document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    }
    try { localStorage.setItem(STORAGE_KEY, lang); } catch { /* ignore */ }
  }, [lang, isRTL]);

  const setLang = useCallback((l) => setLangState(l), []);
  const toggle = useCallback(() => setLangState((l) => (l === 'en' ? 'ar' : 'en')), []);
  const t = useCallback((key) => translations[lang]?.[key] ?? translations.en[key] ?? key, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, isRTL, t, setLang, toggle }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within a LanguageProvider');
  return ctx;
}
