import { sanitizeHtml } from './sanitize';

/** Strip HTML to plain text for PDF fallback / length checks. */
export function htmlToPlainText(html) {
  return String(html || '')
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<\/p>/gi, '\n\n')
    .replace(/<\/li>/gi, '\n')
    .replace(/<li[^>]*>/gi, '• ')
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function buildPolicyDocumentHtml(policy, { isRTL, categoryLabel }) {
  const title = isRTL
    ? (policy.title_ar || policy.title_en || '')
    : (policy.title_en || policy.title_ar || '');
  const description = isRTL
    ? (policy.description_ar || policy.description_en || '')
    : (policy.description_en || policy.description_ar || '');
  const body = isRTL
    ? (policy.body_ar || policy.body_en || '')
    : (policy.body_en || policy.body_ar || '');
  const dir = isRTL ? 'rtl' : 'ltr';
  const align = isRTL ? 'right' : 'left';

  return `
    <div style="width:794px;padding:48px 56px;background:#fff;color:#1a1a1a;font-family:system-ui,-apple-system,Segoe UI,Tahoma,Arial,sans-serif;direction:${dir};text-align:${align};box-sizing:border-box;">
      <div style="border-bottom:2px solid #0f3d2e;padding-bottom:16px;margin-bottom:24px;">
        <div style="font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#5b6b63;margin-bottom:8px;">EduSaga 360 · HR Policy</div>
        <h1 style="font-size:26px;line-height:1.3;margin:0 0 8px;font-weight:700;">${escapeXml(title)}</h1>
        <div style="font-size:12px;color:#5b6b63;">
          ${policy.policy_code ? `<span>${escapeXml(policy.policy_code)}</span> · ` : ''}
          ${categoryLabel ? `<span>${escapeXml(categoryLabel)}</span> · ` : ''}
          <span>${escapeXml(policy.status || 'draft')}</span>
          ${policy.effective_date ? ` · <span>${escapeXml(String(policy.effective_date).slice(0, 10))}</span>` : ''}
        </div>
      </div>
      ${description ? `<p style="font-size:14px;line-height:1.6;color:#334155;margin:0 0 20px;">${escapeXml(description)}</p>` : ''}
      <div style="font-size:13px;line-height:1.7;color:#1e293b;">
        ${sanitizeHtml(body) || `<p>${escapeXml(htmlToPlainText(body) || '—')}</p>`}
      </div>
      <div style="margin-top:40px;padding-top:12px;border-top:1px solid #e2e8f0;font-size:10px;color:#94a3b8;">
        Generated by EduSaga 360 · ${new Date().toISOString().slice(0, 10)}
      </div>
    </div>
  `;
}

function escapeXml(str) {
  return String(str || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Download an HR policy as a multi-page A4 PDF (supports Arabic via HTML canvas).
 */
export async function downloadPolicyPdf(policy, { isRTL = false, categoryLabel = '' } = {}) {
  const { jsPDF } = await import('jspdf');
  const { default: html2canvas } = await import('html2canvas');

  const host = document.createElement('div');
  host.style.cssText = 'position:fixed;left:-10000px;top:0;z-index:-1;';
  host.innerHTML = buildPolicyDocumentHtml(policy, { isRTL, categoryLabel });
  document.body.appendChild(host);

  try {
    const element = host.firstElementChild;
    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      allowTaint: true,
      backgroundColor: '#ffffff',
      logging: false,
    });

    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const imgHeight = (canvas.height * pdfWidth) / canvas.width;

    let heightLeft = imgHeight;
    let position = 0;

    pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, imgHeight);
    heightLeft -= pageHeight;

    while (heightLeft > 1) {
      position -= pageHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    const base =
      policy.policy_code ||
      (isRTL ? policy.title_ar : policy.title_en) ||
      'policy';
    const safe = String(base).replace(/[^\w\u0600-\u06FF.-]+/g, '_').slice(0, 80);
    pdf.save(`${safe}.pdf`);
    return `${safe}.pdf`;
  } finally {
    host.remove();
  }
}
